"""
Kratos Multiphysics Solver Validation Suite
===========================================
Pure-Kratos verification of the RESLO production structural solver
(`kratos_solver.solve_reslo_structure` / `solve_multi_slab_structure`) with
**no external solver dependency** — every reference result is a closed-form
classical plate-theory value or an analytical expectation.

Licensing note: this suite previously cross-compared against OpenSeesPy, whose
license restricts it to academic/non-commercial use. OpenSeesPy and its
`opensees_solver.py` wrapper have been permanently removed from this repository
to keep the whole product commercial-use clean (see docs/ENGINEERING_AUDIT.md).

All meshes are generated by the deterministic structured right-triangle builder
below, so the suite runs on hosts without gmsh (and without libGLU).

Test matrix:
  1. Simply supported square plate vs Reissner-Mindlin thick-plate deflection
  2. Flat slab on corner columns with edge beams — stability & plausibility band
  3. Interior column mushroom panel — global equilibrium (column reaction vs
     total applied load) + hogging curvature concentration at the column
     (read from the deflection field) + bowl silhouette.
     (Punching-shear *design checks* are computed by the TypeScript design
     layer — the sole design-code path in the product — not by the backend
     Kratos solver, so they are asserted in the frontend vitest suite.)
  4. Solver linearity & determinism — load scaling q -> 2q doubles the
     response exactly; repeated solves are bit-stable; response min/max
     aggregates are consistent with the nodal field.
  5. Two-span continuous slab — ETABS edge-constraint acceptance test:
     two meshed slabs joined across a full edge must reproduce the
     single-piece plate deflection field pointwise; plus one-way strip
     deflection/moment benchmarks and support hogging sign.

Author: Structural Engineering Audit
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
import pytest
from models import (
    MeshRequest, FEMMesh, FEMNode, Triangle, SlabGeometry, WallSupport,
    Point2D, AnalysisRequest, ColumnSupport, BeamDef
)
from kratos_solver import solve_reslo_structure


# ─────────────────────── structured rectangular mesh ───────────────────────
def structured_rect_mesh(x0, x1, y0, y1, mesh_size, id_start=1):
    """Deterministic structured right-triangle mesh of a rectangle.

    Returns (FEMMesh, next_free_node_id). Diagonal orientation alternates in a
    union-jack-free (single diagonal per cell) layout.
    """
    nx = max(1, int(round((x1 - x0) / mesh_size)))
    ny = max(1, int(round((y1 - y0) / mesh_size)))
    dx = (x1 - x0) / nx
    dy = (y1 - y0) / ny
    nodes = []
    idmap = {}
    nid = id_start
    for j in range(ny + 1):
        for i in range(nx + 1):
            idmap[(i, j)] = nid
            nodes.append(FEMNode(id=nid, x=x0 + i * dx, y=y0 + j * dy))
            nid += 1
    elements = []
    eid = 1
    for j in range(ny):
        for i in range(nx):
            n0 = idmap[(i, j)]
            n1 = idmap[(i + 1, j)]
            n2 = idmap[(i + 1, j + 1)]
            n3 = idmap[(i, j + 1)]
            elements.append(Triangle(id=eid, nodeIds=[n0, n1, n2])); eid += 1
            elements.append(Triangle(id=eid, nodeIds=[n0, n2, n3])); eid += 1
    mesh = FEMMesh(
        nodeCount=len(nodes), elementCount=len(elements),
        nodes=nodes, elements=elements,
        minAngle=45.0, maxAspectRatio=max(dx, dy) / min(dx, dy),
        meshQuality='Structured'
    )
    return mesh, nid


# ─────────────────────────────── Test 1 ───────────────────────────────
def _mindlin_series_wmax(a=4.0, q=5000.0, E=25e9, nu=0.2, h=0.2, kappa=5.0/6.0):
    """Exact Mindlin (first-order shear) centre deflection of the SSSS plate,
    double-sine series with per-harmonic shear amplification
    (1 + D*(alpha^2+beta^2)/(kappa*G*h)). Kirchhoff limit is kappa -> inf."""
    D = E * h**3 / (12.0 * (1.0 - nu**2))
    G = E / (2.0 * (1.0 + nu))
    w = 0.0
    for m in range(1, 80, 2):
        for n in range(1, 80, 2):
            al, be = m * np.pi / a, n * np.pi / a
            wk = 16.0 * q / (np.pi**2 * D * m * n * (al * al + be * be)**2)
            w += wk * (1.0 + D * (al * al + be * be) / (kappa * G * h)) \
                 * np.sin(al * a / 2) * np.sin(be * a / 2)
    return w


def test_simply_supported_square_plate_kratos():
    """4m x 4m flat slab, walls on all edges — exact Mindlin series reference.

    Historical note: the legacy reference '0.561 mm' was calibrated against a
    load double-application defect and was ~2x the true theoretical value
    (exact Mindlin w_max = 0.3029 mm for this plate)."""
    w_exact = _mindlin_series_wmax()
    assert abs(w_exact - 0.3029e-3) < 0.002e-3, "series reference drifted"

    deviations = []
    for ms in (0.25, 0.20):
        mesh, _ = structured_rect_mesh(0, 4, 0, 4, ms)
        tol = 0.005
        wall_node_ids = [
            i + 1 for i, n in enumerate(mesh.nodes)
            if abs(n.y) < tol or abs(n.y - 4) < tol or abs(n.x) < tol or abs(n.x - 4) < tol
        ]
        analysis_req = AnalysisRequest(
            mesh=mesh,
            thickness=0.2,
            elasticModulus=25e9,
            poissonRatio=0.2,
            uniformLoad=5.0,
            selfWeight=0.0,
            wallNodeIds=wall_node_ids,
            columnNodeIds=[],
            columnHeights=[],
            columnStiffnesses=[],
            columnWidths=[],
            columnDepths=[],
            beamNodeIdA=[],
            beamNodeIdB=[],
            beamWidths=[],
            beamDepths=[],
            beamElasticModuli=[]
        )
        res_kratos = solve_reslo_structure(analysis_req)
        assert res_kratos.success, f"Kratos solver failed: {res_kratos.error}"
        wz = {d.nodeId: d.wz for d in res_kratos.nodeDeflections}
        w_max = max(abs(w) for w in wz.values())
        dev = abs(w_max - w_exact) / w_exact
        deviations.append(dev)
        print(f"\nSSSS mesh={ms}: w_max={w_max*1000:.4f} mm, dev vs Mindlin = {dev*100:.2f}%")
        assert dev < 0.05, f"Deflection deviation {dev*100:.2f}% exceeds 5% threshold"
    # Mesh refinement must not degrade accuracy (convergence direction)
    assert deviations[-1] <= deviations[0] + 0.005, "refinement degraded accuracy"


# ─────────────────────────────── Test 2 ───────────────────────────────
def test_square_plate_with_beams_and_columns_kratos():
    """4m x 4m slab on 4 corner columns with perimeter edge beams — solver
    stability and deflection plausibility band."""
    mesh, _ = structured_rect_mesh(0, 4, 0, 4, 1.0)

    columns = [
        ColumnSupport(position=Point2D(x=0, y=0), width=0.3, depth=0.3, height=3.0),
        ColumnSupport(position=Point2D(x=4, y=0), width=0.3, depth=0.3, height=3.0),
        ColumnSupport(position=Point2D(x=4, y=4), width=0.3, depth=0.3, height=3.0),
        ColumnSupport(position=Point2D(x=0, y=4), width=0.3, depth=0.3, height=3.0)
    ]
    beams = [
        BeamDef(startPoint=Point2D(x=0, y=0), endPoint=Point2D(x=4, y=0)),
        BeamDef(startPoint=Point2D(x=4, y=0), endPoint=Point2D(x=4, y=4)),
        BeamDef(startPoint=Point2D(x=4, y=4), endPoint=Point2D(x=0, y=4)),
        BeamDef(startPoint=Point2D(x=0, y=4), endPoint=Point2D(x=0, y=0))
    ]

    col_node_ids = []
    col_stiff = []
    for col in columns:
        best_nid = 1
        best_dist = 999.0
        for i, n in enumerate(mesh.nodes):
            d = np.hypot(n.x - col.position.x, n.y - col.position.y)
            if d < best_dist:
                best_dist = d
                best_nid = i + 1
        col_node_ids.append(best_nid)
        col_stiff.append(4 * 25e9 * (0.3 * 0.3**3 / 12) / 3.0)

    beamNodeIdA = []
    beamNodeIdB = []
    beamWidths = []
    beamDepths = []
    beamElasticModuli = []

    for beam in beams:
        bestA_nid = 1
        bestA_dist = 999.0
        bestB_nid = 1
        bestB_dist = 999.0
        for i, n in enumerate(mesh.nodes):
            dA = np.hypot(n.x - beam.startPoint.x, n.y - beam.startPoint.y)
            dB = np.hypot(n.x - beam.endPoint.x, n.y - beam.endPoint.y)
            if dA < bestA_dist:
                bestA_dist = dA
                bestA_nid = i + 1
            if dB < bestB_dist:
                bestB_dist = dB
                bestB_nid = i + 1
        beamNodeIdA.append(bestA_nid)
        beamNodeIdB.append(bestB_nid)
        beamWidths.append(0.3)
        beamDepths.append(0.4)
        beamElasticModuli.append(25e9)

    analysis_req = AnalysisRequest(
        mesh=mesh,
        thickness=0.2,
        elasticModulus=25e9,
        poissonRatio=0.2,
        uniformLoad=5.0,
        selfWeight=0.0,
        wallNodeIds=[],
        columnNodeIds=col_node_ids,
        columnHeights=[3.0] * 4,
        columnStiffnesses=col_stiff,
        columnWidths=[0.3] * 4,
        columnDepths=[0.3] * 4,
        beamNodeIdA=beamNodeIdA,
        beamNodeIdB=beamNodeIdB,
        beamWidths=beamWidths,
        beamDepths=beamDepths,
        beamElasticModuli=beamElasticModuli
    )

    res_kratos = solve_reslo_structure(analysis_req)
    assert res_kratos.success, f"Kratos solver failed: {res_kratos.error}"

    wz_kratos = {d.nodeId: d.wz for d in res_kratos.nodeDeflections}
    max_w_kratos = max(abs(w) for w in wz_kratos.values())
    print(f"\nBeam-Col Max wz Kratos: {max_w_kratos*1000:.6f} mm")

    assert 0.1e-3 < max_w_kratos < 2.0e-3, \
        f"Deflection {max_w_kratos*1000:.3f} mm outside plausibility band [0.1, 2.0] mm"


# ─────────────────────────────── Test 3 ───────────────────────────────
def test_interior_column_mushroom_equilibrium():
    """6m x 6m slab on ONE central column (mushroom panel).

    Physics under test:
      1. Global equilibrium — with a single support, the column reaction must
         equal the total applied load. The column is a real 3D beam element
         (axial rigidity EA/H, fully fixed base), so R = EA/H * head settlement.
      2. Moment concentration — the global peak hogging moment must occur in
         the elements incident to the column (singular point support).
      3. Bowl silhouette — free edges sag; the supported centre settles least
         in magnitude among the extreme deflections... i.e. the max-|w| node
         lies on the free boundary, not at the column.
    """
    mesh, _ = structured_rect_mesh(0, 6, 0, 6, 1.0)

    best_nid = 1
    best_dist = 999.0
    for i, n in enumerate(mesh.nodes):
        d = np.hypot(n.x - 3.0, n.y - 3.0)
        if d < best_dist:
            best_dist = d
            best_nid = i + 1

    analysis_req = AnalysisRequest(
        mesh=mesh,
        thickness=0.25,
        elasticModulus=25e9,
        poissonRatio=0.2,
        uniformLoad=10.0,
        selfWeight=6.25,
        wallNodeIds=[],
        columnNodeIds=[best_nid],
        columnHeights=[3.0],
        columnWidths=[0.4],
        columnDepths=[0.4],
        beamNodeIdA=[], beamNodeIdB=[], beamWidths=[], beamDepths=[], beamElasticModuli=[]
    )

    res = solve_reslo_structure(analysis_req)
    assert res.success, f"Kratos solver failed: {res.error}"

    wz = {d.nodeId: d.wz for d in res.nodeDeflections}

    # 1. Global equilibrium through the column axial deformation:
    #    R = EA/H * |w_head|   (M25 => E = 5000*sqrt(25) MPa = 25 GPa)
    w_head = abs(wz[best_nid])
    EA_over_H = 25e9 * (0.4 * 0.4) / 3.0            # N/m
    R_kN = EA_over_H * w_head / 1000.0
    W_total = (10.0 + 6.25) * 36.0                  # kN  (UDL + self-weight) x area
    dev = abs(R_kN - W_total) / W_total
    print(f"\nMushroom Equilibrium: w_head={w_head*1e3:.4f} mm -> R={R_kN:.2f} kN "
          f"vs total load {W_total:.2f} kN ({dev*100:.2f}% deviation)")
    assert dev < 0.05, f"Column reaction equilibrium deviation {dev*100:.2f}% exceeds 5%"
    # Exact axial prediction: w = W*H/(EA)  (beam column formulation verified)
    assert abs(w_head - W_total * 1000.0 / EA_over_H) * EA_over_H / 1000.0 < 0.05 * W_total

    pos = {n.id: (n.x, n.y) for n in mesh.nodes}

    # 2. Hogging curvature concentration at the column (from the deflection
    #    field, structured 1m grid): kappa = d2w/dx2 at the support must be
    #    far larger than anywhere on the free boundary — the punching hump.
    def w_at(x, y):
        nid = min(pos, key=lambda k: (pos[k][0] - x)**2 + (pos[k][1] - y)**2)
        return wz[nid]
    kappa_col = w_at(2, 3) - 2 * w_at(3, 3) + w_at(4, 3)          # /1.0^2 m spacing
    kappa_edge = w_at(0, 2) - 2 * w_at(0, 3) + w_at(0, 4)
    D = 25e9 * 0.25**3 / (12.0 * (1.0 - 0.2**2))
    M_hog = -D * kappa_col / 1000.0                               # kN-m/m (w +down => hogging < 0)
    print(f"Column curvature: kappa_col={kappa_col*1e3:.4f}/m -> M_hog={M_hog:.2f} kN-m/m "
          f"(free-edge kappa={kappa_edge*1e3:.4f})")
    assert kappa_col > 0.0, "No hogging curvature at the column — support singularity missing"
    assert M_hog < 0.0, "Hogging sign convention broken at column"
    # Ratio is grid-limited: the point-support singularity smears over one 1m
    # element ring (measured ratio 2.9 at 1m mesh; it grows with refinement).
    assert abs(kappa_col) > 2.0 * abs(kappa_edge), \
        "Curvature not concentrated at the column (peeling pattern broken)"

    # 3. Bowl silhouette: max-|w| node lies on the free boundary, the
    #    supported centre settles least.
    nid_max = max(wz, key=lambda k: abs(wz[k]))
    x_m, y_m = pos[nid_max]
    on_free_edge = min(x_m, 6 - x_m, y_m, 6 - y_m) < 1e-9
    print(f"Max |w|={abs(wz[nid_max])*1e3:.4f} mm at ({x_m:.1f},{y_m:.1f}); "
          f"column settlement {w_head*1e3:.4f} mm")
    assert on_free_edge, f"Max deflection at interior ({x_m},{y_m}) — not a bowl silhouette"
    assert w_head < abs(wz[nid_max]), "Column settles more than the free edges — nonphysical"


# ─────────────────────────────── Test 4 ───────────────────────────────
def test_solver_linearity_and_determinism():
    """Fundamental solver invariants on the 4m x 4m SSSS plate:
      - Linearity: doubling the load doubles every nodal deflection.
      - Determinism: identical requests produce identical responses
        (no RNG, no uninitialised memory paths).
      - Response aggregates (maxWz) are consistent with the nodal field.
    (Wood-Armer/design-moment fields are produced exclusively by the
    TypeScript design layer; backend responses intentionally carry
    deflections only — see docs/ETABS_PARITY_REPORT.md.)
    """
    def solve(q):
        mesh, _ = structured_rect_mesh(0, 4, 0, 4, 0.25)
        tol = 0.005
        wall_ids = [i + 1 for i, n in enumerate(mesh.nodes)
                    if abs(n.y) < tol or abs(n.y - 4) < tol or abs(n.x) < tol or abs(n.x - 4) < tol]
        req = AnalysisRequest(
            mesh=mesh, thickness=0.2, elasticModulus=25e9, poissonRatio=0.2,
            uniformLoad=q, selfWeight=0.0, wallNodeIds=wall_ids,
            columnNodeIds=[], columnHeights=[], columnStiffnesses=[], columnWidths=[], columnDepths=[],
            beamNodeIdA=[], beamNodeIdB=[], beamWidths=[], beamDepths=[], beamElasticModuli=[])
        r = solve_reslo_structure(req)
        assert r.success, r.error
        return r

    r5 = solve(5.0)
    r10 = solve(10.0)
    r5b = solve(5.0)

    w5 = {d.nodeId: d.wz for d in r5.nodeDeflections}
    w10 = {d.nodeId: d.wz for d in r10.nodeDeflections}
    w5b = {d.nodeId: d.wz for d in r5b.nodeDeflections}

    # Linearity: w(2q) == 2 * w(q) to solver precision
    scale_err = max(abs(w10[k] - 2.0 * w5[k]) for k in w5) / max(abs(v) for v in w5.values())
    print(f"\nLinearity: max relative deviation of w(10) vs 2*w(5) = {scale_err:.3e}")
    assert scale_err < 1e-9, f"Solver non-linear under load scaling ({scale_err:.2e})"

    # Determinism
    det_err = max(abs(w5[k] - w5b[k]) for k in w5)
    print(f"Determinism: max |dw| between identical solves = {det_err:.3e} m")
    assert det_err < 1e-15, "Non-deterministic solver output"

    # Aggregate consistency
    wmax_field = max(abs(v) for v in w5.values())
    assert abs(r5.maxWz - wmax_field) < 1e-9 * max(1.0, wmax_field), \
        f"maxWz aggregate {r5.maxWz} inconsistent with field {wmax_field}"


# ───────────── Test 5 — two-span continuous slab (ETABS edge-constraint acceptance) ─────────────
def test_two_span_continuous_slab_joint_equivalence():
    """ETABS edge-constraint acceptance criterion: TWO 4x4 slabs joined across
    their full shared edge (coincident grids -> coincident-node merging, the
    production Scenario-2 path) must reproduce the ONE-PIECE 8x4 plate
    deflection field pointwise. Walls on x=0, x=4, x=8 (interior support line
    at the joint). Long edges y=0/y=4 free -> one-way strip action dominates:
      interior span peak w_max ~= 0.00542*q*L^4/D  (fixed-pinned plate strip)
      support hogging  M = q*L^2/8 = 10.0 kN-m/m (sign-checked via curvature)
    (Non-conformal T-junction tying via MPCs is covered in test_mpc_interface.py.)
    """
    E, NU, H, Q = 25e9, 0.2, 0.2, 5.0
    D = E * H**3 / (12.0 * (1.0 - NU**2))

    def solve_mesh(mesh):
        wall_nids = [n.id for n in mesh.nodes
                     if abs(n.x) < 0.05 or abs(n.x - 8) < 0.05 or abs(n.x - 4) < 0.05]
        req = AnalysisRequest(
            mesh=mesh, thickness=H, elasticModulus=E, poissonRatio=NU,
            uniformLoad=Q, selfWeight=0.0, wallNodeIds=wall_nids,
            columnNodeIds=[], columnHeights=[], columnStiffnesses=[], columnWidths=[], columnDepths=[],
            beamNodeIdA=[], beamNodeIdB=[], beamWidths=[], beamDepths=[], beamElasticModuli=[])
        r = solve_reslo_structure(req)
        assert r.success, r.error
        return r

    # (i) one-piece 8x4 plate
    single_mesh, _ = structured_rect_mesh(0, 8, 0, 4, 0.25)
    res_single = solve_mesh(single_mesh)

    # (ii) two 4x4 slabs merged across the joint exactly as Scenario-2 does
    m1, _ = structured_rect_mesh(0, 4, 0, 4, 0.25)
    m2, _ = structured_rect_mesh(4, 8, 0, 4, 0.25, id_start=len(m1.nodes) + 1)
    combined_nodes, node_map1, node_map2 = [], {}, {}
    for n in m1.nodes:
        nid = len(combined_nodes) + 1
        node_map1[n.id] = nid
        combined_nodes.append(FEMNode(id=nid, x=n.x, y=n.y))
    for n in m2.nodes:
        coincident = False
        for cn in combined_nodes:
            if ((cn.x - n.x)**2 + (cn.y - n.y)**2)**0.5 < 0.12:
                node_map2[n.id] = cn.id
                coincident = True
                break
        if not coincident:
            nid = len(combined_nodes) + 1
            node_map2[n.id] = nid
            combined_nodes.append(FEMNode(id=nid, x=n.x, y=n.y))
    combined_elements = []
    for e in m1.elements:
        combined_elements.append(Triangle(
            id=len(combined_elements) + 1, nodeIds=[node_map1[i] for i in e.nodeIds]))
    for e in m2.elements:
        combined_elements.append(Triangle(
            id=len(combined_elements) + 1, nodeIds=[node_map2[i] for i in e.nodeIds]))
    two_mesh = FEMMesh(
        nodeCount=len(combined_nodes), elementCount=len(combined_elements),
        nodes=combined_nodes, elements=combined_elements,
        minAngle=45.0, maxAspectRatio=1.0, meshQuality='Structured')
    res_two = solve_mesh(two_mesh)

    wz1 = {d.nodeId: d.wz for d in res_single.nodeDeflections}
    wz2 = {d.nodeId: d.wz for d in res_two.nodeDeflections}
    pos1 = {n.id: (n.x, n.y) for n in single_mesh.nodes}

    # Position->deflection maps allow node-id-free comparison across both cases
    field1 = {p: wz1[nid] for nid, p in pos1.items()}
    field2 = {(n.x, n.y): wz2[n.id] for n in combined_nodes}
    wmax_ref = max(abs(v) for v in wz1.values())

    # ETABS equivalence: two-piece == one-piece, pointwise
    max_gap = max(abs(field1[p] - field2[p]) for p in field1 if p in field2)
    rel_gap = max_gap / wmax_ref
    print(f"\nJoint equivalence: max |w_two-piece - w_one-piece| = {max_gap*1e3:.6f} mm "
          f"({rel_gap*100:.3f}% of max)")
    assert rel_gap < 0.002, \
        f"Two-piece joint departs from single-piece plate by {rel_gap*100:.2f}% (> 0.2%)"

    # Wall-line restraint at the interior support
    line_w = [abs(wz1[nid]) for nid, (x, y) in pos1.items() if abs(x - 4.0) < 0.01]
    assert line_w and max(line_w) < 1e-6, "Interior support line not restrained"

    # One-way strip reference: interior centreline per-span peak
    w_strip = 0.00542 * (Q * 1000.0) * 4.0**4 / D           # fixed-pinned plate strip
    prof = [(x, wz1[nid]) for nid, (x, y) in pos1.items() if abs(y - 2.0) < 0.01
            for x in [pos1[nid][0]] if x < 4.0]
    w_span_peak = max(w for _, w in prof)
    dev_strip = abs(w_span_peak - w_strip) / w_strip
    print(f"Span peak (centreline) = {w_span_peak*1e3:.4f} mm vs strip {w_strip*1e3:.4f} mm "
          f"({dev_strip*100:.1f}%)")
    assert dev_strip < 0.12, "Two-span strip deflection outside 12% band of strip theory"

    # Support hogging via FD curvature at the interior support centreline node:
    # M = -D*d2w/dx2  (w positive downward; hogging < 0), strip exact = 10.0
    def w_at(x, y):
        nid = min(pos1, key=lambda k: (pos1[k][0] - x)**2 + (pos1[k][1] - y)**2)
        return wz1[nid]
    dx = 0.25
    kappa_sup = (w_at(4 - dx, 2) - 2 * w_at(4, 2) + w_at(4 + dx, 2)) / dx**2
    M_hog = -D * kappa_sup / 1000.0
    kappa_span = (w_at(1.75 - dx, 2) - 2 * w_at(1.75, 2) + w_at(1.75 + dx, 2)) / dx**2
    M_sag = -D * kappa_span / 1000.0
    print(f"Curvature moments: M_hog(x=4) = {M_hog:.2f} kN-m/m (strip 10.0, sign < 0); "
          f"M_sag(peak) = {M_sag:.2f} (sign > 0)")
    assert M_hog < 0.0, "No hogging over the interior support — continuity broken"
    assert abs(M_hog) > 0.60 * 10.0, "Hogging magnitude not mobilised (< 60% of strip value)"
    assert M_sag > 0.0, "Spans not sagging"

    # Symmetry of the continuous pair (mirrored spans)
    span1 = [wz1[nid] for nid, (x, y) in pos1.items() if abs(x - 2.0) < 0.13 and abs(y - 2.0) < 0.13]
    span2 = [wz1[nid] for nid, (x, y) in pos1.items() if abs(x - 6.0) < 0.13 and abs(y - 2.0) < 0.13]
    assert span1 and span2
    sym = abs(max(span1) - max(span2)) / wmax_ref
    assert sym < 0.01, f"Span symmetry broken ({sym*100:.2f}%)"
